language: node_js
node_js:
  - "0.12"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install
  - npm run bower

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

services:
  - postgresql
